name: Timesheet Reminders

on:
  schedule:
    - cron: '* 10 * * 5'

jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Reminder
        run: ./send.sh
        env:
           SENDGRID_API_KEY: ${{secrets.SENDGRID_API_KEY}}
