name: Timesheet Reminders

on:
  push:
  ## schedule:
    ## - cron: '* 10 * * 4'

jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run:  curl --request POST \ --url https://api.sendgrid.com/v3/mail/send \--header "Authorization: Bearer ${{ secrets.SENDGRID_API }}" \--header 'Content-Type: application/json' \--data '{"personalizations": [{"to": [{"email": "me@mikebeach.co.uk"}]}],"from": {"email": "test@example.com"},"subject": "Sending with SendGrid is Fun","content": [{"type": "text/plain", "value": "and easy to do anywhere, even with cURL"}]}'