name: Timesheet Reminders

on:
  push:
    branches: 
      - master

jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Reminder
        run: ./send.sh
